export {
  type AgentExtraFeaturesV2 as OnsmartAgentExtraFeatures,
  type OnsmartSchedulingConfig,
  type AgentToolEntry,
  parseAgentExtraFeatures,
  parseOnsmartExtraFeatures,
  resolveOnsmartWelcomeMessage,
  resolveWelcomeMessage,
  resolveSchedulingConfig,
  buildOnsmartExtraFeaturesJson,
  serializeAgentExtraFeatures,
  getEnabledTools,
  isToolEnabled,
  buildToolKey,
} from './agent-extra-features'
